language: python
cache: pip3
os:
  - linux
python:
  - 3.6
install:
  - pip3 install -r "requirements.txt"
before_script:
    - echo "http://b1twis3.me/" > subdomains.txt
script:
  - python3 b1tmass.py -f subdomains.txt -O evil.com -c
