language: python
cache: pip3
os:
  - linux
python:
  - 3.6
install:
  - pip3 install validators
before_script:
    - echo "http://b1twis3.me/" > subdomains.txt
script:
  - python3 b1tmass.py subdomains.txt evil.com
